apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ .Values.redis.namespace }}
  labels:
    app: {{ .Values.redis.labels.app }}
spec:
  selector:
    app: {{ .Values.redis.labels.app }}
  ports:
  - name: redis
    port: {{ .Values.redis.service.port }}
    targetPort: {{ .Values.redis.service.targetPort }}