apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: {{ .Values.db.namespace }}
  labels:
    app: {{ .Values.db.labels.app }}
spec:
  selector:
    app: {{ .Values.db.labels.app }}
  ports:
  - name: db-service
    port: {{ .Values.db.service.port }}
    targetPort: {{ .Values.db.service.targetPort }}