apiVersion: v1
kind: Service
metadata:
  name: vote
  namespace: {{ .Values.vote.namespace }}
spec:
  selector:
    app: {{ .Values.vote.labels.app }}
  ports:
    - port: {{ .Values.vote.service.port }}
      targetPort: {{ .Values.vote.service.targetPort }}
  type: {{ .Values.vote.service.type }}